//> using scala "3.3.0"
//> using lib "org.typelevel::cats-effect:3.5.1"
//> using lib "org.typelevel::cats-core:2.10.0"
//> using lib "org.scodec::scodec-bits::1.1.37"
//> using lib "org.typelevel::spire:0.18.0"